Test for http username
sindresorhus/linkify-urls pull request #6
Opened 2017-09-07 16:13 UTC by bfred-it

Example (noticeable with Refined GitHub): https://github.com/scieloorg/opac_proc/blob/46d9f826d2519573b99418f11da1ce3f87bfa7eb/requirements.txt#L12-L14

Related: should it support `git+http` urls at all?

2017-09-07 16:20 UTC, kevva requested changes

2017-09-07 16:20 UTC, kevva commented on test.js
> +	t.is(m('https://user@sindresorhus.com/@foo'), '<a href="https://user@sindresorhus.com/@foo">https://user@sindresorhus.com/@foo</a>');
`t.is` => `t.fail`

2017-09-07 16:42 UTC, kevva requested changes

2017-09-07 16:42 UTC, kevva commented on test.js
> +	t.fail(m('https://user@sindresorhus.com/@foo'), '<a href="https://user@sindresorhus.com/@foo">https://user@sindresorhus.com/@foo</a>');
Sorry, my bad 😿 . This line needs to be in a separate `test`:

```js
test.failing('supports username in url', t => {
    t.is(m('https://user@sindresorhus.com/@foo'), '<a href="https://user@sindresorhus.com/@foo">https://user@sindresorhus.com/@foo</a>');
});
```

2017-09-08 04:48 UTC, sindresorhus commented
> Related: should it support git+http urls at all?

Is there really any point? Clicking it wouldn't work anyway.

2017-09-08 05:57 UTC, bfred-it commented
@sindresorhus it's mostly about expectations. Also perhaps people have git URL handlers that open SourceTree for example.

2017-09-08 06:06 UTC, sindresorhus commented
Who's' expectations though? I definitely wouldn't expect such URLs to be linkified. I actually don't want it at all, as it creates noise and gives a false expectation that they will work.

> Also perhaps people have git URL handlers that open SourceTree for example.

That would be a minority, and everyone else would have to pay with useless links and wasted time clicking them and then realizing it's not working.

2017-09-08 06:07 UTC, sindresorhus commented
I see that `-e git+https://github.com/scieloorg/xylose@1.17.5#egg=xylose` got linkified in your referenced example. I don't think we should linkify that either as it obviously doesn't work. In your linked case, it would make more sense for Octolinker to handle those.

2017-09-08 07:09 UTC, bfred-it commented
How do we detect that though? The regex will have to look for the character that comes before `http` as well

2017-09-08 07:30 UTC, sindresorhus commented
We would need a lookbehind regex pattern, which is still just a draft standard. Alternatively we could change it to also match `git+` and then filter the URLs afterwards.

2017-09-22 09:45 UTC, sindresorhus commented
@bfred-it Could you change the test to what we've discussed? (Not allowing + prefixed URLs)

2017-09-22 10:54 UTC, bfred-it commented
Not sure of how to do that :D

2017-09-22 13:05 UTC, sindresorhus commented
I'm only talking about the test, not the implementation. This is what I meant: https://github.com/sindresorhus/linkify-urls/commit/4db31ab79d62dc0adf6b3c086a6a68f955343918 :)

2017-09-22 13:06 UTC, sindresorhus commented
Continued in https://github.com/sindresorhus/linkify-urls/issues/7

2017-09-22 13:22 UTC, bfred-it commented
That’s unrelated to this PR, URLs with user:pass are still real HTTP and browsers can handle them

2017-09-22 16:21 UTC, sindresorhus commented
Oops, I was too focused on the + stuff.

2017-10-29 10:42 UTC, merged